package me.belucky.exam.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQueryCond<M extends BaseTQueryCond<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setQuestionType(java.lang.Integer questionType) {
		set("question_type", questionType);
	}
	
	public java.lang.Integer getQuestionType() {
		return getInt("question_type");
	}

	public void setQueryValue(java.lang.String queryValue) {
		set("query_value", queryValue);
	}
	
	public java.lang.String getQueryValue() {
		return getStr("query_value");
	}

}
