package me.belucky.exam.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQuestionSelectOption<M extends BaseTQuestionSelectOption<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setQuestionId(java.lang.Integer questionId) {
		set("question_id", questionId);
	}
	
	public java.lang.Integer getQuestionId() {
		return getInt("question_id");
	}

	public void setSelectKey(java.lang.String selectKey) {
		set("select_key", selectKey);
	}
	
	public java.lang.String getSelectKey() {
		return getStr("select_key");
	}

	public void setSelectDesc(java.lang.String selectDesc) {
		set("select_desc", selectDesc);
	}
	
	public java.lang.String getSelectDesc() {
		return getStr("select_desc");
	}

}
