package me.belucky.exam.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQuestionRecord<M extends BaseTQuestionRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setQuestionId(java.lang.Integer questionId) {
		set("question_id", questionId);
	}
	
	public java.lang.Integer getQuestionId() {
		return getInt("question_id");
	}

	public void setQuestionType(java.lang.Integer questionType) {
		set("question_type", questionType);
	}
	
	public java.lang.Integer getQuestionType() {
		return getInt("question_type");
	}

	public void setSeq(java.lang.Integer seq) {
		set("seq", seq);
	}
	
	public java.lang.Integer getSeq() {
		return getInt("seq");
	}

	public void setSelectOption(java.lang.String selectOption) {
		set("select_option", selectOption);
	}
	
	public java.lang.String getSelectOption() {
		return getStr("select_option");
	}

	public void setCorrectOption(java.lang.String correctOption) {
		set("correct_option", correctOption);
	}
	
	public java.lang.String getCorrectOption() {
		return getStr("correct_option");
	}

	public void setCorrectFlag(java.lang.String correctFlag) {
		set("correct_flag", correctFlag);
	}
	
	public java.lang.String getCorrectFlag() {
		return getStr("correct_flag");
	}

	public void setUserNo(java.lang.String userNo) {
		set("user_no", userNo);
	}
	
	public java.lang.String getUserNo() {
		return getStr("user_no");
	}

	public void setCreateDt(java.util.Date createDt) {
		set("create_dt", createDt);
	}
	
	public java.util.Date getCreateDt() {
		return get("create_dt");
	}

}
