package me.belucky.exam.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTQuestion<M extends BaseTQuestion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setQuestionType(java.lang.Integer questionType) {
		set("question_type", questionType);
	}
	
	public java.lang.Integer getQuestionType() {
		return getInt("question_type");
	}

	public void setSeq(java.lang.Integer seq) {
		set("seq", seq);
	}
	
	public java.lang.Integer getSeq() {
		return getInt("seq");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setSelectAnswer(java.lang.String selectAnswer) {
		set("select_answer", selectAnswer);
	}
	
	public java.lang.String getSelectAnswer() {
		return getStr("select_answer");
	}

	public void setExamId(java.lang.Integer examId) {
		set("exam_id", examId);
	}
	
	public java.lang.Integer getExamId() {
		return getInt("exam_id");
	}

}
