package me.belucky.exam.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTCodeValue<M extends BaseTCodeValue<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setValueDesc(java.lang.String valueDesc) {
		set("value_desc", valueDesc);
	}
	
	public java.lang.String getValueDesc() {
		return getStr("value_desc");
	}

}
