package me.belucky.exam.model.table;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_code_value", "id", TCodeValue.class);
		arp.addMapping("t_exam", "id", TExam.class);
		arp.addMapping("t_query_cond", "id", TQueryCond.class);
		arp.addMapping("t_question", "id", TQuestion.class);
		arp.addMapping("t_question_record", "id", TQuestionRecord.class);
		arp.addMapping("t_question_select_option", "id", TQuestionSelectOption.class);
		arp.addMapping("t_user", "id", TUser.class);
	}
}

