package me.belucky.exam.model.table;

import me.belucky.exam.model.table.base.BaseTCodeValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TCodeValue extends BaseTCodeValue<TCodeValue> {
	public static final TCodeValue dao = new TCodeValue().dao();
}
