package me.belucky.exam.model.table;

import me.belucky.exam.model.table.base.BaseTExam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TExam extends BaseTExam<TExam> {
	public static final TExam dao = new TExam().dao();
}
