package me.belucky.exam.model.table;

import me.belucky.exam.model.table.base.BaseTQuestionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestionRecord extends BaseTQuestionRecord<TQuestionRecord> {
	public static final TQuestionRecord dao = new TQuestionRecord().dao();
}
