package me.belucky.exam.model.table;

import me.belucky.exam.model.table.base.BaseTQueryCond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQueryCond extends BaseTQueryCond<TQueryCond> {
	public static final TQueryCond dao = new TQueryCond().dao();
}
