package me.belucky.exam.model.table;

import me.belucky.exam.model.table.base.BaseTQuestionSelectOption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestionSelectOption extends BaseTQuestionSelectOption<TQuestionSelectOption> {
	public static final TQuestionSelectOption dao = new TQuestionSelectOption().dao();
}
