package me.belucky.exam.model.table;

import me.belucky.exam.model.table.base.BaseTQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TQuestion extends BaseTQuestion<TQuestion> {
	public static final TQuestion dao = new TQuestion().dao();
}
