package me.belucky.exam.model.table;

import me.belucky.exam.model.table.base.BaseTUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TUser extends BaseTUser<TUser> {
	public static final TUser dao = new TUser().dao();
}
